"""Add Category Item_Category and Items Relation

Revision ID: 5c1bf390fc38
Revises: 698ac846c3dc
Create Date: 2025-02-02 17:27:13.317852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c1bf390fc38'
down_revision: Union[str, None] = '698ac846c3dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('type_of', postgresql.ENUM('PIZZA', 'APPETIZERS_AND_SIDES', 'PASTA', 'SALADS', 'BEVERAGE', 'DESSERTS', 'SANDWICH_AND_SUBS', 'CALZONES_AND_STROMBOLIS', 'OTHER', name='food_type'), nullable=False),
    sa.Column('description', sa.VARCHAR(length=250), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('name')
    )
    op.create_table('itemCategories',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.uid'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'category_id'),
    sa.UniqueConstraint('item_id', 'category_id', name='uq_item_category')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itemCategories')
    op.drop_table('categories')
    # ### end Alembic commands ###
