"""Add Items and Category Image Column

Revision ID: 5d4bd51f5442
Revises: f106bfb8b60a
Create Date: 2025-03-22 09:44:26.354484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5d4bd51f5442'
down_revision: Union[str, None] = 'f106bfb8b60a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'image',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('items', 'image',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'image',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('categories', 'image',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    # ### end Alembic commands ###
