"""add phone, is_verified and password field in Customer

Revision ID: b8154367acd9
Revises: f7ab1f816c6b
Create Date: 2025-03-01 09:43:08.530592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b8154367acd9'
down_revision: Union[str, None] = 'f7ab1f816c6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('phone', sa.VARCHAR(length=20), nullable=False))
    op.add_column('customers', sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False))
    op.add_column('customers', sa.Column('is_verified', sa.BOOLEAN(), nullable=False))
    op.create_unique_constraint(None, 'customers', ['password_hash'])
    op.create_unique_constraint(None, 'customers', ['phone'])
    op.create_unique_constraint('uq_item_category', 'itemCategories', ['item_id', 'category_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_item_category', 'itemCategories', type_='unique')
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_column('customers', 'is_verified')
    op.drop_column('customers', 'password_hash')
    op.drop_column('customers', 'phone')
    # ### end Alembic commands ###
