"""Order and Order-Items adjustment and minor tweeks

Revision ID: cb57a483a451
Revises: 5d4bd51f5442
Create Date: 2025-03-28 09:06:40.196943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cb57a483a451'
down_revision: Union[str, None] = '5d4bd51f5442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'customers', ['user_id'])
    op.alter_column('orders', 'customer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('orders_customer_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'customers', ['customer_id'], ['uid'], ondelete='SET NULL')
    op.alter_column('payments', 'order_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('payments_order_id_fkey', 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'orders', ['order_id'], ['uid'], ondelete='SET NULL')
    op.create_unique_constraint(None, 'staffs', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staffs', type_='unique')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key('payments_order_id_fkey', 'payments', 'orders', ['order_id'], ['uid'])
    op.alter_column('payments', 'order_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_customer_id_fkey', 'orders', 'customers', ['customer_id'], ['uid'], ondelete='CASCADE')
    op.alter_column('orders', 'customer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'customers', type_='unique')
    # ### end Alembic commands ###
