"""Add Items and Category Image Column with Null True (Temporary)

Revision ID: f106bfb8b60a
Revises: 9ba51faaa362
Create Date: 2025-03-22 09:32:57.187541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f106bfb8b60a'
down_revision: Union[str, None] = '9ba51faaa362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('image', sa.VARCHAR(length=250), nullable=True))
    op.add_column('items', sa.Column('image', sa.VARCHAR(length=250), nullable=True))
    op.alter_column('items', 'description',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.VARCHAR(length=250),
               existing_nullable=False)
    op.drop_column('items', 'image')
    op.drop_column('categories', 'image')
    # ### end Alembic commands ###
