"""Add Payment Table

Revision ID: f7ab1f816c6b
Revises: f73e6ecbc367
Create Date: 2025-02-06 17:40:44.899375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7ab1f816c6b'
down_revision: Union[str, None] = 'f73e6ecbc367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.VARCHAR(length=250), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('payment_method', postgresql.ENUM('UPI', 'NEFT', 'CREDIT_CARD', 'DEBIT_CARD', 'CASH', name='payment_method'), nullable=False),
    sa.Column('payment_status', postgresql.ENUM('PENDING', 'COMPLETED', name='payment_status'), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    # ### end Alembic commands ###
