"""Changed Dine In Enum

Revision ID: fc78b8a9f8e2
Revises: cb57a483a451
Create Date: 2025-03-31 11:41:48.572695

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "fc78b8a9f8e2"
down_revision: Union[str, None] = "cb57a483a451"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE delivery_type ADD VALUE 'DINE_IN' AFTER 'DINE_OUT'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
